task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: 'data/people_snapshot/male-5-sport'
    human: 'male-5-sport'
    ann_file: 'data/people_snapshot/male-5-sport/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/male-5-sport'
    human: 'male-5-sport'
    ann_file: 'data/people_snapshot/male-5-sport/params.npy'
    split: 'test'

vis_relight_cfg:
    smpl_model_ckpt: 'data/trained_model/if_nerf/male5s/latest.pth'

train_relight_cfg:
    smpl_model_ckpt: 'data/trained_model/if_nerf/male5s/latest.pth'


# data options
ratio: 1.
num_train_frame: 300
