task: 'if_nerf'
gpus: [0]

smplx: False
train_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
train_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'
test_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
test_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'

network_module: 'lib.networks.latent_xyzc'
network_path: 'lib/networks/latent_xyzc.py'
renderer_module: 'lib.networks.renderer.if_clight_renderer'
renderer_path: 'lib/networks/renderer/if_clight_renderer.py'

trainer_module: 'lib.train.trainers.if_nerf_clight'
trainer_path: 'lib/train/trainers/if_nerf_clight.py'

evaluator_module: 'lib.evaluators.if_nerf'
evaluator_path: 'lib/evaluators/if_nerf.py'

visualizer_module: 'lib.visualizers.if_nerf'
visualizer_path: 'lib/visualizers/if_nerf.py'

train_dataset:
    data_root: 'data/people_snapshot/female-3-casual'
    human: 'female-3-casual'
    ann_file: 'data/people_snapshot/female-3-casual/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/female-3-casual'
    human: 'female-3-casual'
    ann_file: 'data/people_snapshot/female-3-casual/params.npy'
    split: 'test'

train:
    batch_size: 1
    collator: ''
    lr: 5e-4
    weight_decay: 0
    epoch: 400
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 1000
    num_workers: 4

test:
    batch_size: 1
    collator: ''

ep_iter: 500
save_ep: 100
eval_ep: 1000

# rendering options
i_embed: 0
xyz_res: 10
view_res: 4
raw_noise_std: 0

N_samples: 64
N_importance: 128
N_rand: 1024

perturb: 1
white_bkgd: False

num_render_views: 50

# data options
H: 1080
W: 1080
ratio: 1.
num_train_frame: 230

voxel_size: [0.005, 0.005, 0.005]  # dhw

# record options
log_interval: 1
mask_loss: 0.0
pyramid: True

vis_relight_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_relight_demo_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_relight_demo_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_relight_demo_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_relight_demo_dataset.py'
    network_module: 'lib.networks.relight_microfacet'
    network_path: 'lib/networks/relight_microfacet.py'
    trainer_module: 'lib.train.trainers.relight_direct'
    trainer_path: 'lib/train/trainers/relight_direct.py'
    visualizer_module: 'lib.visualizers.if_nerf_demo'
    visualizer_path: 'lib/visualizers/if_nerf_demo.py'
    renderer_module: 'lib.networks.renderer.if_clight_renderer_msk'
    renderer_path: 'lib/networks/renderer/if_clight_renderer_msk.py'
    skip_eval: True
    mlp_chunk: 65536
    mlp_width: 256
    mlp_depth: 4
    mlp_skip_at: 1
    xyz_scale: 1.0
    n_freqs_xyz: 10
    n_freqs_ldir: 4
    n_freqs_vdir: 4
    n_freqs: 2
    light_h: 16
    xyz_jitter_std: 0.01
    smooth_use_l1: True
    shape_mode: 'scratch'
    smpl_model_ckpt: 'data/trained_model/if_nerf/female3c/latest.pth'
    olat_inten: 200.
    ambient_inten: 0.
    specular: True
    normal_smooth_weight: 0.01
    lvis_smooth_weight: 0.5
    albedo_slope: 0.77
    albedo_bias: 0.03
    pred_brdf: True
    use_xyz: True
    albedo_smooth_weight: 0.005
    brdf_smooth_weight: 0.00001
    light_tv_weight: 0.000005
    learned_brdf_scale: 1.
    light_init_max: 1
    light_achro_weight: 0.
    achro_light: True
    linear2srgb: True
    normalize_z: False
    fresnel_f0: 0.04
    fix_light: True
    lvis_far: 0.5
    lvis_near: 0.0
    perturb_light: 0.0
    albedo_sparsity: 0.0005
    test:
        sampler: ''


train_relight_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'
    network_module: 'lib.networks.relight_microfacet'
    network_path: 'lib/networks/relight_microfacet.py'
    trainer_module: 'lib.train.trainers.relight_direct'
    trainer_path: 'lib/train/trainers/relight_direct.py'
    skip_eval: True
    mlp_chunk: 65536
    mlp_width: 256
    mlp_depth: 4
    mlp_skip_at: 1
    xyz_scale: 1.0
    n_freqs_xyz: 10
    n_freqs_ldir: 4
    n_freqs_vdir: 4
    n_freqs: 2
    light_h: 16
    xyz_jitter_std: 0.01
    smooth_use_l1: True
    shape_mode: 'scratch'
    use_shape_sup: True
    smpl_model_ckpt: 'data/trained_model/if_nerf/female3c/latest.pth'
    olat_inten: 200.
    ambient_inten: 0.
    normal_loss_weight: 1.
    lvis_loss_weight: 1.
    normal_smooth_weight: 0.01
    lvis_smooth_weight: 0.5
    albedo_slope: 0.77
    albedo_bias: 0.03
    pred_brdf: True
    use_xyz: True
    albedo_smooth_weight: 0.005
    brdf_smooth_weight: 0.00001
    specular: True
    light_tv_weight: 0.000005
    learned_brdf_scale: 1.
    light_init_max: 1
    light_achro_weight: 0.
    achro_light: True
    linear2srgb: True
    normalize_z: False
    fresnel_f0: 0.04
    fix_light: True
    lvis_far: 0.5
    lvis_near: 0.0
    perturb_light: 0.0
    albedo_sparsity: 0.0005



relight_npose_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'

novel_view_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_demo_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_demo_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_demo_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_demo_dataset.py'

    renderer_module: 'lib.networks.renderer.if_clight_renderer_msk'
    renderer_path: 'lib/networks/renderer/if_clight_renderer_msk.py'

    visualizer_module: 'lib.visualizers.if_nerf_demo'
    visualizer_path: 'lib/visualizers/if_nerf_demo.py'

    ratio: 0.5

    test:
        sampler: ''

novel_pose_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_dataset.py'

    renderer_module: 'lib.networks.renderer.if_clight_renderer_msk'
    renderer_path: 'lib/networks/renderer/if_clight_renderer_msk.py'

    visualizer_module: 'lib.visualizers.if_nerf_perform'
    visualizer_path: 'lib/visualizers/if_nerf_perform.py'

    ratio: 0.5

    test:
        sampler: ''

mesh_cfg:
    train_dataset_module: 'lib.datasets.light_stage.monocular_mesh_dataset'
    train_dataset_path: 'lib/datasets/light_stage/monocular_mesh_dataset.py'
    test_dataset_module: 'lib.datasets.light_stage.monocular_mesh_dataset'
    test_dataset_path: 'lib/datasets/light_stage/monocular_mesh_dataset.py'

    network_module: 'lib.networks.latent_xyzc'
    network_path: 'lib/networks/latent_xyzc.py'
    renderer_module: 'lib.networks.renderer.if_mesh_renderer'
    renderer_path: 'lib/networks/renderer/if_mesh_renderer.py'

    visualizer_module: 'lib.visualizers.if_nerf_mesh'
    visualizer_path: 'lib/visualizers/if_nerf_mesh.py'

    mesh_th: 5

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 1
