task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: 'data/people_snapshot/female-1-casual'
    human: 'female-1-casual'
    ann_file: 'data/people_snapshot/female-1-casual/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/female-1-casual'
    human: 'female-1-casual'
    ann_file: 'data/people_snapshot/female-1-casual/params.npy'
    split: 'test'


vis_relight_cfg:
    smpl_model_ckpt: 'data/trained_model/if_nerf/female1c/latest.pth'

train_relight_cfg:
    smpl_model_ckpt: 'data/trained_model/if_nerf/female1c/latest.pth'


# data options
ratio: 1.
num_train_frame: 250
